<html>
<body>
  <div>Пользователи:</div>
  <ul>
    <li>Джон</li>
    <li>Пит</li>
  </ul>
</body>
</html>
document.body.children[0]
document.body.children[1]
document.body.lastElementChild.lastElementChild
